all:  
  vars:
    ansible_python_interpreter: /usr/bin/env python3
    ansible_user: root
    id: apollo
    version: 3.0.0
  hosts:
    master1:
      ansible_connection: docker
  children:
    default:
      vars:
        blueprint:
          master:
            count: 1
            spec:
              extra: ''
              image: rancher/k3s:v1.19.5-k3s1
              meta:
                labels:
                  cluster: apollo
                name: master
              provider:
                name: docker
          node:
            count: 0
            spec:
              extra: ''
              image: rancher/k3s:v1.19.5-k3s1
              meta:
                labels:
                  cluster: apollo
                name: node
              provider:
                name: docker
      hosts:
        master1:
    master:
      hosts:
        master1:
    node:
      hosts:
        