- name: "handling prereqs"
  include_tasks:
    file: "prereq.yml"
    apply:
      tags:
        - create
        - install
  tags:
    - never
    - create
    - install

- name: downloading k3s
  include_tasks:
    file: "download.yml"
    apply:
      tags:
        - create
        - install
  tags:
    - never
    - create
    - install

- name: handling raspberrypi
  include_tasks:
    file: "raspberrypi.yml"
    apply:
      tags:
        - create
        - install
  tags:
    - never
    - create
    - install

- name: setting up master
  include_tasks:
    file: "master.yml"
    apply:
      tags:
        - create
        - install
  when: "'master' in group_names"
  tags:
    - never
    - create
    - install

- name: setting up node
  include_tasks:
    file: "node.yml"
    apply:
      tags:
        - create
        - install
  when: "'node' in group_names"
  tags:
    - never
    - create
    - install

# - name: resetting cluster
#   include_tasks:
#     file: "reset.yml"
#     apply:
#       tags:
#         - delete
#   tags:
#     - never
#     - delete
#   when: "'node' in group_names"