- name: "deleting {{ inventory_hostname }}"
  community.general.docker_container:
    name: "{{ inventory_hostname }}"
    state: absent
  register: server
  delegate_to: localhost
  tags:
    - delete

- name: showing server
  debug:
    var: server
    verbosity: 1
  tags:
    - delete
  when:
    - server.changed
