- name: "deleting server"
  hcloud_server:
    name: "{{ inventory_hostname }}"
    api_token: "{{ lookup('env','HCLOUD_TOKEN', allow_undefined=false) }}"
    state: absent
  when: "'kubernetes' not in group_names"
  delegate_to: localhost

# - name: add to inventory
#   add_host:
#     groups: 
#       - deleted_hosts
#       - cluster
#     hostname: "{{ server_name }}"

# - name: show inventory
#   debug:
#     var: hostvars
#     verbosity: 1