---
- name: "deleting {{ apollo_cluster }}"
  hosts: "{{ apollo_cluster }}:!kubernetes"
  gather_facts: false
  connection: local
  tasks:
    - name: debug
      debug:
        var: hostvars[inventory_hostname]
        verbosity: 1
      tags:
        - delete
      when: "'kubernetes' not in group_names"

    - name: deleting server
      include_role:
        name: "{{ hostvars[inventory_hostname]['provider'] }}/server/delete"
        apply:
          tags:
            - delete
      tags:
        - delete
      when: "'kubernetes' not in group_names"

- name: "deleting {{ apollo_cluster }} from space"
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: deleting cluster inventory
      file:
        state: absent
        path: "{{ apollo_space_dir }}/{{ apollo_cluster }}/inventory.yml"
      tags:
        - never
        - delete
      delegate_to: localhost

    - name: deleting cluster kubeconfig
      file:
        state: absent
        path: "{{ apollo_space_dir }}/{{ apollo_cluster }}/config"
      tags:
        - never
        - delete
      delegate_to: localhost

    - name: refresh inventory
      meta: refresh_inventory
      tags:
        - delete
