---
- name: "checking conditions"
  hosts: localhost
  gather_facts: yes
  vars:
    apollo_runtime_version: "{{ lookup('env','APOLLO_VERSION') }}"
  tasks:
    - fail: 
        msg: "You're running {{ apollo_runtime_version }} but specified version {{ version }} in .apollorc.yml"
      when:
        - hostvars[inventory_hostname]['version'] != ''
        - apollo_runtime_version != hostvars[inventory_hostname]['version']
        - not lookup('env','APOLLO_FORCE')|bool
  tags:
    - always
    - version
    - install

- name: "installing cluster"
  hosts: 
    - "{{ apollo_cluster }}"
  become: true
  tasks:
    - include_role:
        name: k3s
        allow_duplicates: no
        apply:
          tags:
            - orchestrator
            - k3s
      tags:
        - orchestrator
        - k3s
        - install
      when:
        - provider != 'docker'
  tags:
    - create
    - install
